name: 'Dastardly Scan Action'
description: 'Runs a Dastardly scan against a target site'
on:
    push:
        branches:
          - main
        pull_request:

steps:
  - name: Run Dastardly Action Step
    uses: PortSwigger/dastardly-github-action@main
    with:
      target-url: 'https://ginandjuice.shop'

jobs:
  build:
    permissions:
      issues: write
    runs-on: ubuntu-latest
