name: Burp scanner

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Burp Suite Dastardly Action
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://ginandjuice.shop'
